#ifndef GLOBAL_VARS_H
#define GLOBAL_VARS_H

// CONTROL PINS
#define PWM_CONTROL 25

// THERMISTOR PINS
#define TERM1 26
#define TERM2 27

// ROTARY ENCODER PINS
#define ROTARY_ENCODER_A_PIN 5
#define ROTARY_ENCODER_B_PIN 4
#define ROTARY_ENCODER_BUTTON_PIN 15
#define ROTARY_ENCODER_VCC_PIN -1
#define ROTARY_ENCODER_STEPS 4
#define ACCELERATION_VALUE 100

// DHT22 PINS
#define DHT_SENSOR_PIN 14
#define DHT_SENSOR_TYPE DHT22

#endif // GLOBAL_VARS_H
